#!/bin/sh

#pacman
echo $'pacman'
pacman -Sl | grep installed | sed 's/\[installed\]//g' | sed 's/core//g' | sed 's/extra//g' | sed 's/community//g' | sed -e 's/\([0-9]\+\)//g' | sed 's/\.//g' | sed 's/\-/ /g' | sed 's/://g'

#yay
echo $'\nyay'
yay -Sl | grep nstalled | sed 's/\[installed]//g' | sed 's/\[Installed]//g' | sed 's/core//g' | sed 's/extra//g' | sed 's/community//g' | sed 's/aur//g' | sed -e 's/\([0-9]\+\)//g' | sed 's/\.//g' | sed 's/\-/ /g' | sed 's/://g'
echo $'\n'
